Pull Request 3
oluwajuwon8/Portfolio-Project pull request #3
Opened 2021-11-02 10:25 UTC by oluwajuwon8

Contact form section.

2021-11-02 11:43 UTC, carlos-ssh requested changes
Hi @oluwajuwon8 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._
![changesrequested](https://user-images.githubusercontent.com/22258274/139840085-8a64ea10-e140-49d1-81dc-18173d352377.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-02 11:43 UTC, carlos-ssh commented on index.html
>      <form class="method">
- Kindly use only one ``form`` tag and nest ``input`` for ``email``, ``text`` and ``name``.
- Follow the project requirements requested:
![Screen Shot 2021-11-02 at 5 40 45](https://user-images.githubusercontent.com/22258274/139839759-1320d263-3ab0-4a33-8ba1-e18e7d9fb3e8.png)


**_[QUICK REFERENCE FOR FORM IN HTML @ W3SCHOOLS](https://www.w3schools.com/html/html_forms.asp)_**

2021-11-02 21:55 UTC, mikethreels requested changes
Hi Azeezat, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] because the previous CR didn't mention it the following is not a requirement however, I strongly advise you to make these changes before you merge this PR. make sure you indent your code, in order to make it more readable.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-02 21:55 UTC, mikethreels commented on index.html
> +    <form  class="contact" action="https://formspree.io/f/{form_id}" method="post">
- [ ] great work on wrapping the `<input>` tags inside the `<form>` tag 👍 however as the previous CR mentioned as well, try and make sure you follow the project requirements to the letter. in this case, the submission of your form is not working because you're using the placeholder text in your action. for a detailed explanation go to [the Formspree webpage](https://formspree.io/), click on "get started" and follow the instructions

2021-11-03 11:32 UTC, omar-labana approved these changes
Hi @oluwajuwon8, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-03 11:33 UTC, merged

2021-11-04 07:20 UTC, abdessalem1998 commented
Hi  @oluwajuwon8

- [ ] Your project is complete! i have only small remarks lines 160/161, you can use only one line to target the all the direction of the margin inside  each individual direcyion, this will reduce the code lines and make your code a bit simpler.